<a href="https://colab.research.google.com/github/prince2004coder/Data-Science-/blob/main/pandas(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

dct = {
    'name' : ['tom', 'nick', 'krish', 'jack'],
    'age' : [20, 21, 19, 18],
    'roll' : [1, 2, 3, 4]
}

df = pd.DataFrame(dct,index=['a','b','c','d'])

#df1 = pd.DataFrame(dct)


display(df)
#display(df1)

    name  age  roll
a    tom   20     1
b   nick   21     2
c  krish   19     3
d   jack   18     4

In [26]:
df = pd.read_csv('student_data.csv')
df.head(4)#give first  values you input

df.tail(3)#give last   values you input


df.shape #rows and colums of data we give

#df.info()
#df.describe()
#q1,q2,q3 qualitile ,,,iqr-- q3-q1
#q1,q2,q3---25,50,75(%)


df.columns

df.index

#df[['study_hours','internet_usage']]

#df.study_hours

df.iloc[0:5]#give row data


#df2 = df.loc[df['study_hours']==11]

#df.loc[4]

#df.loc[df['assignments_completed']==8]
#df.iloc[]

study_hours                  11
attendance                   60
sleep_hours                   7
internet_usage                6
assignments_completed        10
previous_score               45
exam_score                100.0
placement_status         Placed
Name: 2, dtype: object

In [27]:
df = pd.read_csv('student_data.csv')

df.loc[df['assignments_completed']==8].iloc[1]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [49]:
df = pd.read_csv('student_data.csv')


#df[df['assignments_completed']>8]

df["age"]= 20


#rename columns \


#df.rename(columns = {'assignments_completed':'assign_completed'},inplace = True)
df


df.drop(index=[2],inplace = True)
df.drop(columns= ['age'],inplace = True)
df

df.dropna(inplace = True)
df

df.sort_values(by = 'exam_score',ascending = True,inplace = True)
df

#try isnull,,notnull,unique(for a series. only ),,fillna

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
8805,1,63,4,11,6,54,26.67,Not Placed
186,1,47,5,10,0,46,26.89,Not Placed
3141,1,55,8,8,5,40,27.82,Not Placed
7566,1,58,7,3,6,38,31.41,Not Placed
9499,2,64,5,10,6,37,31.43,Not Placed
...,...,...,...,...,...,...,...,...
6271,4,59,4,10,16,69,100.00,Placed
6274,2,70,7,3,18,86,100.00,Placed
6275,9,97,9,4,14,71,100.00,Placed
6276,10,70,4,3,1,72,100.00,Placed
9993,10,86,9,9,15,63,100.00,Placed